[package]
name = "raphael-bench-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
axum-github-webhook-extract = "0.3.0"
axum-standardwebhooks = "1.0.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
